##Linting a way to write a ode in a good way or standard way or some different things.
## This is done by using flake8 
name : Linting

on : 
  push : 
    branches : [master]

jobs : 
  Linting_proecess:
      strategy : 
        matrix : 
            os : ["ubuntu-latest" , "windows-latest" , "macos-latest"]
      runs-on: ${{matrix.os}}

      steps:
        - name : Checkout code 
          uses : actions/checkout@v3

        - name : Set up python 
          uses : actions/setup-python@v4
          with : 
            python-version : '3.8'
          
        - name : Install flake8
          run : |
            python -m pip install --upgrade pip
            pip install flake8
        - name: Run flake8
          run : |
            flake8 app.py